packages:
  - apps/*
  - packages/*

catalog:
  '@hono/zod-validator': ^0.9.0
  '@tailwindcss/vite': ^4.3.3
  '@types/node': ^24.12.0
  hono: ^4.13.3
  solid-js: ^1.9.15
  tailwindcss: ^4.3.3
  typescript: ~7.0.2
  vite: ^8.2.1
  vite-plugin-solid: ^2.11.14
  zod: ^4.4.3

allowBuilds:
  lefthook: true
  electron: true
  electron-winstaller: true
