packages:
  - apps/*
  - packages/*

catalog:
  '@tailwindcss/vite': ^4.3.3
  '@types/node': ^24.10.12
  '@types/react': ^19.2.18
  '@types/react-dom': ^19.2.4
  '@vitejs/plugin-react': ^6.1.0
  oxc-transform-react: ^0.145.0
  react: ^19.2.8
  react-dom: ^19.2.8
  tailwindcss: ^4.3.3
  typescript: ~7.0.2
  vite: ^8.2.1

allowBuilds:
  lefthook: true
  electron: true
  electron-winstaller: true
